name: autofix
on: pull_request
jobs:
  autofix:
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'autofix') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Sort
        run: |
          sort abc.txt > abc.txt.sorted; mv abc.txt.sorted abc.txt
          git commit -am "Sort abc.txt"
      - name: Fix spelling
        run: |
          pip3 install codespell
          codespell --write-changes --ignore-words-list xdescribe
          git commit -am "Accept codespell replacements"
      - name: Set vars
        id: vars
        run: |
          echo ::set-output name=branch-name::"autofix/${{ github.head_ref }}"
          # https://stackoverflow.com/questions/3878624/how-do-i-programmatically-determine-if-there-are-uncommitted-changes
          echo ::set-output name=files-changed-count::$(git status --porcelain=v1 2>/dev/null | wc -l)
      - name: Inspect vars
        run: echo files-changed-count=${{ steps.vars.outputs.files-changed-count }}
      - name: Create Pull Request
        if: steps.vars.outputs.files-changed-count > 0
        uses: peter-evans/create-pull-request@v3
        with:
          title: Autofix ${{ github.head_ref }}
          body: This is an auto-generated PR with fixes for \#${{github.event.pull_request.number}} by autofix.
          labels: autofix
          branch: ${{ steps.vars.outputs.branch-name }}
      - name: Fail if files changed
        if: steps.vars.outputs.files-changed-count > 0
        run: exit 1
